targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true

#flutter packages pub run build_runner build
