name: flutter_weather_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  google_fonts: ^2.1.0
  hydrated_bloc: ^7.0.0
  json_annotation: ^4.0.0
  path_provider: ^2.0.2
  pedantic: ^1.11.1
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
  json_serializable: ^4.0.0
  mocktail: ^0.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/
