name: infinite_list
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  #
  flutter_bloc: ^7.1.0
  http: ^0.13.3
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.1.0
  mocktail: ^0.1.4

dependency_overrides:
  bloc: ^7.1.0
  flutter_bloc: ^7.1.0
flutter:
  uses-material-design: true
