 
include: package:very_good_analysis/analysis_options.2.3.0.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_redundant_argument_values: false
    prefer_const_literals_to_create_immutables: false
    unnecessary_const: false