name: todo_repository
description: A new Flutter package project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cloud_firestore: ^1.0.5
  equatable: ^2.0.3
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
